### PR TITLE
Update XMB_IT.TXT

### PR DESCRIPTION
**Pull request by DigiOhhh**
Fix Italian translations

Some remarks: in Italian capital letters are only used with first names, surnames, city names, and so on, which is why I've removed them. I've also deleted articles (like ‘the’ in English) and prepositions (like “of, by, from” in English), not only because there is none in the English version but also because it doesn't feel very natural to have them in a settings menu. Lastly, I think the word ‘launcher’ does not need any translation and/or there is no good way to translate it along with the word ‘autoboot’; I've considered a few alternatives but simply using ‘launcher’ sounds much better. Might be my Computer Science background talking though

### CODE REVIEW

**Comment by JoseAaronLopezGarcia** [comment]
Looks good, but the only thing that caughts my eye is this one:
Supporto plugin obsoleti

Is "obsoleti" the proper wording here? I mean an updated (not at all obsolete) plugin might need this patch if for whatever reason it was only made to work with ms0. Then again, the original uses the word "old" which I also think is misleading.

**Comment by DigiOhhh** [comment]
> Looks good, but the only thing that caughts my eye is this one: Supporto plugin obsoleti
> 
> Is "obsoleti" the proper wording here? I mean an updated (not at all obsolete) plugin might need this patch if for whatever reason it was only made to work with ms0. Then again, the original uses the word "old" which I also think is misleading.

Ok, then maybe "classici" is better. I've used "obsoleti" because I was thinking of plugins that have not been updated to support PSP Go, but then again some plugins may have just been updated and the developer might not want to add support to Go for whatever reason. So my misconception was that the only plugins not supporting Go were the ones that haven't been updated in a while, but this isn't necessarily the case.
Yeah, "classici" is clearly better, even though it's not easy to explain what that option does in such a limited space.

**Comment by JoseAaronLopezGarcia** [comment]
Maybe a better description to that feature would be "Fix incompatible plugins on PSP Go".
I will have to update other languages to feature this change, but I think it's worth it.

**Comment by DigiOhhh** [comment]
in that case I would go with “Correggi incompatibilità plugin su PSP Go”, or “Correggi plugin non compatibili con PSP Go”
Do you want me to fix the pull request with this new translation? I believe you should be able to as well, so if you prefer updating the English version first we can wait.

**Comment by JoseAaronLopezGarcia** [comment]
> in that case I would go with “Correggi incompatibilità plugin su PSP Go”, or “Correggi plugin non compatibili con PSP Go” Do you want me to fix the pull request with this new translation? I believe you should be able to as well, so if you prefer updating the English version first we can wait.

Go ahead and fix it on the PR, I don't mind merging it first and fixing other translations later. I prefer the first sentence as it's shorter and would show better on the PSP screen.

**Comment by JoseAaronLopezGarcia** [comment]
Thanks, merging.

**Pull request merged**
