### PR TITLE
Update XMB_IT.TXT

### PR DESCRIPTION
**Pull request by lorenzofelletti**
Slight modifications to Italian translation.

### CODE REVIEW

**Comment by JoseAaronLopezGarcia** [comment]
Thanks! Merging.

**Comment by JoseAaronLopezGarcia** [comment]
Can you translate this sentence?

Block hibernation on PSP Go

**Comment by lorenzofelletti** [comment]
Sure! I would translate it as "Blocca l'ibernazione sulla PSP Go".

**Comment by JoseAaronLopezGarcia** [comment]
> Sure! I would translate it as "Blocca l'ibernazione sulla PSP Go".

Thanks a lot!

**Comment by lorenzofelletti** [comment]
Could you please provide me some context about the meaning of "hibernation deletion" on PSP Go?

**Comment by JoseAaronLopezGarcia** [comment]
> Could you please provide me some context about the meaning of "hibernation deletion" on PSP Go?

The "Pause Game" feature of PSP Go (aka hibernation), the XMB will delete it if you run another game, this patch prevents this.

**Comment by lorenzofelletti** [comment]
Ok thank you. I would then translate this as "Previeni cancellazione dell'ibernazione su PSP Go".

**Comment by JoseAaronLopezGarcia** [comment]
> Ok thank you. I would then translate this as "Previeni cancellazione dell'ibernazione su PSP Go".

awesome, thanks!

**Pull request merged**
