### PR TITLE
Advanced VSH Menu: "UMD Disc" --> "UMD"

### PR DESCRIPTION
**Pull request by xyzshantaram**
"UMD Disc" is a redundant acronym, UMD already stands for Universal Media Disc :P

### CODE REVIEW

**Comment by xyzshantaram** [comment]
Will probably need translations updated.

**Comment by JoseAaronLopezGarcia** [comment]
For the translations,  you can leave them all as UMD, since the acronym doesn't have to be translated.

**Comment by xyzshantaram** [comment]
Okay, all the translations should also be fixed now. I grepped through the repo but couldn't find anywhere else it had to be updated. Did I miss anything?

**Comment by JoseAaronLopezGarcia** [comment]
Thanks

**Pull request merged**
