### PR TITLE
Polish xmb translation

### PR DESCRIPTION
**Pull request by Kitki30**
Polish xmb translation

### CODE REVIEW

**Comment by Kitki30** [comment]
Can you merge pull request
And i also added Stars at start of xmb apps (that ark shortcuts)

**Comment by JoseAaronLopezGarcia** [comment]
The problem we have is that the XMB doesn't have a configuration for the Polish language.
It only supports English, Spanish, Italian, French, German, Dutch, Russian, Japanese, Korean and Chinese (traditional and simplified). We are limited to those languages for the XMB, but we are not limited on the Custom Launcher (except for the Fonts).

**Comment by JoseAaronLopezGarcia** [comment]
One possible way we could allow custom translations that aren't available in the XMB would be perhaps to allow users to create an XMB_LANG.TXT file in ARK_01234 were they can put their own translation which would be used regardless of the language defined by the user.

**Comment by JoseAaronLopezGarcia** [comment]
I already implemented my idea and it works.

**Comment by Kitki30** [comment]
Ok so it will change english to txt file?

**Comment by Kitki30** [comment]
And what with vsh menu

**Comment by JoseAaronLopezGarcia** [comment]
Extract these files inside ARK_01234 and restart the console:
[ARK_01234.zip](https://github.com/PSP-Archive/ARK-4/files/13046225/ARK_01234.zip)

**Pull request merged**
