### PR TITLE
Refactor vshmenu

### PR DESCRIPTION
**Pull request by pyroesp**
### More refactoring and cleanup

**bug included - DO NOT MERGE AS IS**

English VSH and AVSH work perfectly.
Any other language, the AVSH menu skips over options as if the buttons are pressed more than once, even though that's not the case.
Some debug information is shown in the AVSH menu, see advanced.c for the debug stuff.

Haven't found the issue yet.

Because it's an issue only when using another language, I'm wondering if loading the translation file somehow messes up something and it affects the read keys functionality.

### CODE REVIEW

**Review by krazynez — COMMENTED** [review]
`sceKernelDelayThread(10000);` fixes the direction bug

I added the dalay before `submenu_sel = ROLL_OVER(submenu_sel + direction, 0, SUBMENU_MAX - 1);` in advanced.c

**Comment by krazynez** [comment]
Think this is just good to close now. We have most of these changes and all langs work fine now. Unless there is something I am missing.

**Comment by pyroesp** [comment]
Merged main into refactor and fixed a couple issues so it compiles again.

Tried the vshmenu and the menu skip issue is still present when selecting fg and bg light colors.

**Comment by pyroesp** [comment]
I've tried optimizing blit a bit to see if that would fix the error, but it doesn't.
I also didn't do any tests on if this actually helps (or hinders) the compiler, but they're tricks I used before were I know it helped.

**Comment by pyroesp** [comment]
hopefully menu skip fix:
The `new_buttons_on` variable is what was being used to increase/decrease the menu option.
This variable is updated by the `ui_eat_key` function, which is called by another thread/interrupt (I think).
If the menu loop is going faster than the `ui_eat_key` updates the `pad` and `new_buttons_on` variables, then it is possible that the direction bit is high for a long enough time that the button function is executed more than once which would then increase/decrease the menu option resulting in the skipping bug we saw.

Adding the old_pad to the menu button function should fix this issue.

**Pull request merged**
