### PR TITLE
update chs translation

### PR DESCRIPTION
**Pull request by WanderMax**
update chs translation lang_chs.json, XMB_CHS.TXT
add chs translation satelite_chs.txt

### CODE REVIEW

**Comment by JoseAaronLopezGarcia** [comment]
Thanks!

**Comment by li-fstz** [comment]
satelite_chs.txt 里面的中文不能正常显示

**Comment by WanderMax** [comment]
翻译上解决了，有可能代码上没有读取

**Comment by JoseAaronLopezGarcia** [comment]
I think the problem with Chinese (and also Japanese and Korean) translations is that VSH Menu uses its own font files and it doesn't have one with Chinese characters. We need to review the code that handles reading the font file and figure out the format so we can create a bing font file for Chinese. I know the format of the fonts is 8x8 pixels per character and I think they are encoded in some DOS format.

**Pull request merged**
