### PR TITLE
arkmenu: fixes loading times,faulty directories,usb enabled default

### PR DESCRIPTION
**Pull request by svensvond**
- arkBrowser: speed up loading times for root
- arkBrowser: speed up loading times for folders with isos
- arkBrowser: usb enabled by default
- arkBrowser: fixed directory reads go wrong, see #178

### CODE REVIEW

**Review by krazynez — COMMENTED** [review]
Removing the sizing would remove great file/directory sizes feature that we implemented, USB **SHOULD** not be enabled by default. The hidden directories is out of my realm. 

@JoseAaronLopezGarcia please look into this carefully. I do not recommend this to be merged.

**Comment by svensvond** [comment]
for sizing: true, i prefer opening larger directoies in 5 vs 40 seconds (250 isos+) - i dont care about iso file size. 
At least the filetype verification function should be rearranged.

**Comment by krazynez** [comment]
> for sizing: true, i prefer opening larger directoies in 5 vs 40 seconds (250 isos+) - i dont care about iso file size. At least the filetype verification function should be rearranged.

You don't yes, but not everyone thinks that way. It should be optional then to enable or disable not just removed fully.

**Comment by svensvond** [comment]
Thata true.

Brennen Murphy ***@***.***> schrieb am Mo., 3. Juli 2023,
23:42:

**Comment by JoseAaronLopezGarcia** [comment]
I've left a few comments. Overall the idea is there but it needs to be improved. I specially don't like how it loses features that were requested by other users.

**Comment by svensvond** [comment]
i should have noted that it shoudnt be directly merged, if you would build options for it that would be great. Other than that the order of filetype recognition is a thing that does not harm and speeds up file display a lot. Also the bug-fix should be somehow implemented, my fix is just quick and dirty as i dont know the code that good ..

**Comment by JoseAaronLopezGarcia** [comment]
Alright I will use this PR to cook up something that'll speed up File IO.

**Pull request closed without merging**
