### PR TITLE
Enable Img for iso disc extension

### PR DESCRIPTION
**Pull request by Zer0xFF**
I have a collection of PSP games that are just iso's with extension img, I rather keep as is.

### CODE REVIEW

**Comment by JoseAaronLopezGarcia** [comment]
I'm guessing this works as is with Inferno(?).
What about letting the Custom Launcher detect these too?

**Comment by JoseAaronLopezGarcia** [comment]
Alright this looks good, merging.

**Comment by Zer0xFF** [comment]
great, just to note, there are 2 other extension checks in the project `ARK-4/extras/menus/recovery_classic/proshell.c` (dont know where is that used, so I can't test the change), and `ARK-4/extras/menus/advancedvsh/umdvideo_list.c` (dont have umd isos). (though its just an extension check so no harm in changing them regardless for consistency)

**Comment by JoseAaronLopezGarcia** [comment]
> great, just to note, there are 2 other extension checks in the project `ARK-4/extras/menus/recovery_classic/proshell.c` (dont know where is that used, so I can't test the change), and `ARK-4/extras/menus/advancedvsh/umdvideo_list.c` (dont have umd isos). (though its just an extension check so no harm in changing them regardless for consistency)

I think it should be added for consistency.

**Pull request merged**
